[PRM-628] Separated Call to Action Rows using Estimated/Due status, I…
hmrc/penalties-frontend pull request #121
Opened 2021-09-20 08:10 UTC by Chris-Williams-QA

…T/Unit tests TBD

2021-09-22 10:21 UTC, Chris-Williams-QA commented
Commit has an incorrect name, but regardless everything should be good to go.

2021-09-24 08:53 UTC, LewisMitchell requested changes
Looks good, just a few bits to cleanup. Running AT's now

2021-09-24 08:53 UTC, LewisMitchell commented on it/controllers/IndexControllerISpec.scala
> +      println(parsedBody.select("#late-payment-penalties section").text)
Could you remove this println?

2021-09-24 08:53 UTC, LewisMitchell commented on it/controllers/IndexControllerISpec.scala
> +      println(summaryCardBody.text)
Could you remove this println?

2021-09-24 08:53 UTC, LewisMitchell commented on it/controllers/IndexControllerISpec.scala
> +      //returnLSPDataStub(etmpPayloadWithLPPVATUnpaidAndVATOverviewAndLSPsDue.copy(latePaymentPenalties = paidLatePaymentPenalty))
Could you remove this comment?

2021-09-24 08:53 UTC, LewisMitchell commented on it/controllers/IndexControllerISpec.scala
> +      println(parsedBody.select("#late-payment-penalties section").text)
Could you remove this println?

2021-09-24 08:53 UTC, LewisMitchell commented on it/controllers/IndexControllerISpec.scala
> +        println(parsedBody.select("#what-is-owed").text)
Could you remove this println?

2021-09-24 09:02 UTC, LewisMitchell commented
![image](https://user-images.githubusercontent.com/53828896/134648507-7c86466e-5535-4d52-b36a-36f7ec8bb28e.png)

2021-09-24 09:02 UTC, LewisMitchell approved these changes

2021-09-24 09:03 UTC, merged