PRM-823 Updated summary card to display text
hmrc/penalties-frontend pull request #133
Opened 2021-11-19 16:08 UTC by ruthdas03

2021-11-19 16:20 UTC, LewisMitchell requested changes
Looks good, just some clean-up & formatting tasks

2021-11-19 16:20 UTC, LewisMitchell commented on app/viewmodels/LateSubmissionPenaltySummaryCard.scala
> +                        multiplePenaltyPeriod:Option[Html] = None
```suggestion
                        multiplePenaltyPeriod: Option[Html] = None
```

2021-11-19 16:20 UTC, LewisMitchell commented on app/viewmodels/SummaryCardHelper.scala
> +  private def getMultiplePenaltyPeriodMessage(penalty : PenaltyPoint)(implicit messages: Messages):Option[Html]={
```suggestion
  private def getMultiplePenaltyPeriodMessage(penalty: PenaltyPoint)(implicit messages: Messages): Option[Html] = {
```

2021-11-19 16:20 UTC, LewisMitchell commented on app/viewmodels/SummaryCardHelper.scala
> +    Some(Html(messages("lsp.multiple.penaltyPeriod",dateTimeToString(PenaltyPeriodHelper.sortedPenaltyPeriod(penalty.period.get).reverse.head.submission.dueDate))))
This is some quite complex logic, could you sort it and then do .last:
```suggestion
    Some(Html(messages("lsp.multiple.penaltyPeriod", dateTimeToString(PenaltyPeriodHelper.sortedPenaltyPeriod(penalty.period.get).last.submission.dueDate))))
```

2021-11-19 16:20 UTC, LewisMitchell commented on conf/messages
> +lsp.multiple.penaltyPeriod = The VAT Return due on {0} was also submitted late. <br> HMRC  only applies 1 penalty for late submission in each month.
```suggestion
lsp.multiple.penaltyPeriod = The VAT Return due on {0} was also submitted late. <br> HMRC only applies 1 penalty for late submission in each month.
```

2021-11-19 16:20 UTC, LewisMitchell commented on conf/messages.cy
> +lsp.multiple.penaltyPeriod = The VAT Return due on {0} was also submitted late. <br> HMRC  only applies 1 penalty for late submission in each month.
```suggestion
lsp.multiple.penaltyPeriod = The VAT Return due on {0} was also submitted late. <br> HMRC only applies 1 penalty for late submission in each month.
```

2021-11-19 16:20 UTC, LewisMitchell commented on test/assets/messages/IndexMessages.scala
> +  def lspMultiplePenaltyPeriodMessage(dueDate : String) = s"The VAT Return due on $dueDate was also submitted late. <br> HMRC  only applies 1 penalty for late submission in each month."
```suggestion
  def lspMultiplePenaltyPeriodMessage(dueDate: String) = s"The VAT Return due on $dueDate was also submitted late. <br> HMRC only applies 1 penalty for late submission in each month."
```

2021-11-19 16:20 UTC, LewisMitchell commented on test/viewmodels/SummaryCardHelperSpec.scala
> +        val sampleSummaryCardReturnSubmitted: LateSubmissionPenaltySummaryCard = LateSubmissionPenaltySummaryCard(
You could rename this to expectedResult

2021-11-19 16:20 UTC, LewisMitchell commented on test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
> +    "given multiple penalty period in LSP" should{
```suggestion
    "given multiple penalty period in LSP" should {
```

2021-11-19 16:20 UTC, LewisMitchell commented on test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
> +    "given multiple penalty period in LSPP" should{
```suggestion
    "given multiple penalty period in LSPP" should {
```

2021-11-19 16:20 UTC, LewisMitchell commented on test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
> +    "given no multiple penalty period in LSP" should{
```suggestion
    "given no multiple penalty period in LSP" should {
```

2021-11-19 16:20 UTC, LewisMitchell commented on test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
> +      "show message VAT return submitted earlier in multiple penalty period" in{
```suggestion
      "show message VAT return submitted earlier in multiple penalty period" in {
```

2021-11-19 16:20 UTC, LewisMitchell commented on test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
> +      "show message VAT return submitted earlier in multiple penalty period" in{
```suggestion
      "show message VAT return submitted earlier in multiple penalty period" in {
```

2021-11-19 16:20 UTC, LewisMitchell commented on test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
> +      "show message VAT return submitted earlier in multiple penalty period" in{
Also I'm not sure this test name makes sense - perhaps we could change this to be:
`"no message relating to multiple penalties in the same period should appear" in {`

2021-11-19 16:20 UTC, LewisMitchell commented on test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
> +      "show message VAT return submitted earlier in multiple penalty period" in{
```suggestion
      "show message VAT return submitted earlier in multiple penalty period" in {
```

2021-11-19 16:53 UTC, ruthdas03 commented
> Looks good, just some clean-up & formatting tasks

Updated with the suggested changes

2021-11-22 08:48 UTC, LewisMitchell approved these changes

2021-11-22 08:48 UTC, merged