[PRM-1282]: updated compliace controller and pageHelper to use new model
hmrc/penalties-frontend pull request #180
Opened 2022-05-11 11:32 UTC by BackRowOla

2022-05-12 08:51 UTC, LewisMitchell requested changes

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        LPP2Percentage = Some(2.00),
Could you change this to:
```suggestion
        LPP2Percentage = Some(4.00),
```

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        LPP1HRPercentage = Some(1.00),
Could you change this to:
```suggestion
        LPP1LRPercentage = Some(2.00),
        LPP1HRPercentage = Some(2.00),
```

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        parsedBody.select("#main-content .govuk-summary-list__row").get(0).select("dt").text() shouldBe "Penalty amount (estimate)"
This would be posted, so you should be able to remove the '(estimate)' part

2022-05-12 08:51 UTC, LewisMitchell commented on app/controllers/CalculationController.scala
> +                val warningPenaltyAmount = CurrencyFormatter.parseBigDecimalToFriendlyValue(penalty.get.penaltyAmountOutstanding.get * 2)
Raised with design and ticket created, if the user were to part pay their VAT or part pay their penalty then this data would be misaligned to the true value of the VAT owed. Will merge in with this consideration

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        parsedBody.select("#main-content h2").text() shouldBe "Estimates"
You can remove this because the penalty would be posted, unless you want to keep it as accruing

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +      "return 200 (OK) and render the view correctly when the user has specified a valid penalty ID" in new Setup(true) {
Could you name the parameter in the Setup class

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +      "return 200 (OK) and render the view correctly whe nthe user has specified a valid penalty ID and the VAT is due" in new Setup (true) {
Could you name the parameter in the Setup class

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +      "return 500 (ISE) when the user specifies a penalty not within their data" in new Setup (true) {
Could you name the parameter in the Setup class

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +      "return 300 (SEE_OTHER) when the user is not authorised" in new Setup (true) {
Could you name the parameter in the Setup class and change status to 303
```suggestion
      "return 303 (SEE_OTHER) when the user is not authorised" in new Setup (true) {
```

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +      "return 300 (SEE_OTHER) when the user is not authorised" in new Setup(true) {
Could you name the parameter in the Setup class + change status code
```suggestion
      "return 303 (SEE_OTHER) when the user is not authorised" in new Setup(true) {
```

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +      "return 500 (ISE) when the user specifies a penalty not within their data" in new Setup(true) {
Could you name the parameter in the Setup class

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +      "return 200 (OK) and render the view correctly with Penalty Amount" in new Setup(true) {
Could you name the parameter in the Setup class

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +      "return 200 (OK) and render the view correctly when the user has specified a valid penalty ID (only one interest charge)" in new Setup(true) {
Could you name the parameter in the Setup class

2022-05-12 08:51 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +      "the user has specified a valid penalty ID (parses decimals correctly)" in new Setup(true) {
Could you name the parameter in the Setup class

2022-05-16 10:46 UTC, LewisMitchell requested changes

2022-05-16 10:46 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +          "4% of £10,000.00 (VAT amount unpaid on 23 March 2021) + 4% of £10,000.00 (VAT amount unpaid on 7 April 2021)"
This should be 2% of £10k

2022-05-16 14:35 UTC, BackRowOla commented on app/viewmodels/CalculationPageHelper.scala
> +        val percentageOfOutstandingAmtCharged = lpp.LPP1LRPercentage.get + lpp.LPP1HRPercentage.get
I see, 4% did seemed like a lot

2022-05-18 07:26 UTC, LewisMitchell approved these changes
Looks good from what I can see, could rebase?

2022-05-20 14:15 UTC, LewisMitchell requested changes

2022-05-20 14:15 UTC, LewisMitchell commented on app/controllers/CalculationController.scala
> +    logger.debug(s"[CalculationController][getOldPenaltyData] - Foo Bar!")
Could you remove this please?

2022-05-20 14:15 UTC, LewisMitchell commented on app/controllers/CalculationController.scala
> +        val penalty: Option[LPPDetails] = payload.latePaymentPenalty.flatMap(_.details.find(_.principalChargeReference == penaltyId))
This is going to be refactored later to use principalChargeReference & isAdditional flag

2022-05-20 14:15 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +      "return 200 (OK) and render the view correctly whe nthe user has specified a valid penalty ID and the VAT is due" in new Setup(isFSEnabled = true) {
```suggestion
      "return 200 (OK) and render the view correctly when the user has specified a valid penalty ID and the VAT is due" in new Setup(isFSEnabled = true) {
```

2022-05-20 14:15 UTC, LewisMitchell commented on app/services/PenaltiesService.scala
> +
Can you not use the v2 penalties service?

2022-05-20 14:15 UTC, LewisMitchell commented on test/services/PenaltiesServiceSpec.scala
> +
This should be redundant if you use the v2 penalties service

2022-05-20 14:15 UTC, LewisMitchell commented on app/controllers/CalculationController.scala
> +    penaltiesService.getPenaltyDetailsFromEnrolmentKey(EnrolmentKeys.constructMTDVATEnrolmentKey(request.vrn)).map {
should be able to use the v2 penalties service

2022-05-23 15:26 UTC, AndrewRButcher approved these changes

2022-05-23 15:26 UTC, merged