[PRM-213]: added routing to penaltes appeals plus penaltyId to model
hmrc/penalties-frontend pull request #27
Opened 2021-05-11 16:08 UTC by BackRowOla

2021-05-11 17:06 UTC, BackRowOla commented
test this please

2021-05-12 10:16 UTC, LewisMitchell requested changes
LGTM. Just a few changes

2021-05-12 10:16 UTC, LewisMitchell commented on app/controllers/IndexController.scala
> +    logger.debug(s"[IndexController][appealPenalty] redirect to appeals frontend with id $penaltyId")
The [appealPenalty] should be [redirectToAppeals]

2021-05-12 10:16 UTC, LewisMitchell commented on app/viewmodels/SummaryCard.scala
>                          footerUrl: String = "#",
I think we can remove the footer url now

2021-05-12 10:16 UTC, LewisMitchell commented on test/views/IndexViewSpec.scala
>            //TODO: change this when we appeal penalties link
we can remove the //TODO now

2021-05-12 10:16 UTC, LewisMitchell commented on test/controllers/IndexControllerSpec.scala
> +        status(result) shouldBe SEE_OTHER
Could we add a check for the redirect location through `redirectLocation(result)`?

2021-05-12 11:03 UTC, LewisMitchell approved these changes
LGTM. Just running the AT's.

2021-05-12 11:09 UTC, merged