[PRM-1926] Added url to Check what you owe page
hmrc/penalties-frontend pull request #284
Opened 2022-10-26 14:14 UTC by JBlacklaws

2022-10-27 08:54 UTC, AndrewRButcher requested changes

2022-10-27 08:54 UTC, AndrewRButcher commented on conf/application.conf
> +  url = "http://localhost:9152/vat-through-software/what-you-owe"
This will need an app-config base PR to override in envs

2022-10-27 08:54 UTC, AndrewRButcher commented on test/views/IndexViewSpec.scala
> +        docWithPenalties.select(Selectors.button).attr("href").contains("http://localhost:9152/vat-through-software/what-you-owe") shouldBe true
Avoiding using shouldBe true
```suggestion
        docWithPenalties.select(Selectors.button).attr("href") shouldBe "http://localhost:9152/vat-through-software/what-you-owe"
```

2022-10-27 08:54 UTC, AndrewRButcher commented on test/views/IndexViewSpec.scala
> +        docWithPenalties.select(Selectors.button).attr("href").contains("http://localhost:9152/vat-through-software/what-you-owe") shouldBe true
Avoiding using shouldBe true
```suggestion
        docWithPenalties.select(Selectors.button).attr("href") shouldBe "http://localhost:9152/vat-through-software/what-you-owe"
```

2022-10-27 09:07 UTC, AndrewRButcher commented on conf/application.conf
> +  url = "http://localhost:9152/vat-through-software/what-you-owe"
app config base pr created and config moved to urls section
https://github.com/hmrc/app-config-base/pull/7771

2022-10-31 08:47 UTC, AndrewRButcher commented
Rebased ✅

2022-10-31 09:49 UTC, LewisMitchell approved these changes

2022-10-31 10:39 UTC, merged