PRM-1981 Welsh updates
hmrc/penalties-frontend pull request #288
Opened 2022-11-10 08:43 UTC by AndrewRButcher

2022-11-11 12:30 UTC, LewisMitchell requested changes
Could you rebase plz?

2022-11-11 13:21 UTC, LewisMitchell submitted a review, later dismissed
Happy before rebase

2022-11-14 09:38 UTC, AndrewRButcher commented
ATs updated with changes https://github.com/hmrc/penalties-acceptance-tests/pull/213

2022-11-14 10:24 UTC, LewisMitchell approved these changes

2022-11-14 10:24 UTC, merged