[PRM-2313] Added TPP content to LPP1
hmrc/penalties-frontend pull request #329
Opened 2023-02-20 15:40 UTC by JBlacklaws

Trader:
![Screenshot 2023-02-20 at 11 31 36](https://user-images.githubusercontent.com/58850837/220149093-9a5568f0-f9e9-4c80-be72-49e3540a6095.png)
Agent:
![Screenshot 2023-02-20 at 11 32 14](https://user-images.githubusercontent.com/58850837/220149106-a4369a4e-ad2c-4877-962b-37fa4117348b.png)

2023-02-20 16:10 UTC, JBlacklaws commented
Requires: https://github.com/hmrc/penalties/pull/237

2023-02-21 08:42 UTC, LewisMitchell requested changes
Could you rebase please?

2023-02-21 10:15 UTC, LewisMitchell requested changes

2023-02-21 10:15 UTC, LewisMitchell commented on app/viewmodels/CalculationPageHelper.scala
> +          value => value.exists(ttp => {
I think this can be reverted back to how it was

2023-02-21 10:42 UTC, LewisMitchell requested changes

2023-02-21 10:42 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +  val penaltyDetailsWithDay15ChargeTPPActive: GetPenaltyDetails = samplePenaltyDetails.copy(
```suggestion
  val penaltyDetailsWithDay15ChargeTTPActive: GetPenaltyDetails = samplePenaltyDetails.copy(
```

2023-02-21 11:18 UTC, LewisMitchell approved these changes

2023-02-21 11:19 UTC, merged