Prm 2551
hmrc/penalties-frontend pull request #348
Opened 2023-05-11 14:48 UTC by RoheelArshad

2023-05-12 08:14 UTC, LewisMitchell commented
Ideally this needs to be rebased and not pulled from main

2023-05-12 08:38 UTC, LewisMitchell requested changes

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        penaltyAmountAccruing = 0,
This (penaltyAmountAccruing) would be 400, also I don't think it would have an outstanding amount anymore

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        penaltyAmountPosted = 277,
Posted would be outstanding + paid. So it would be 400.

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        penaltyAmountPosted = 277,
Posted would be outstanding + paid. So it would be 400.

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        penaltyAmountAccruing = 0,
This (penaltyAmountAccruing) would be 400, also I don't think it would have an outstanding amount anymore

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        penaltyAmountPosted = 113.45,
Posted would be outstanding + paid. So it would be 123.45.

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        penaltyAmountAccruing = 0,
This (penaltyAmountAccruing) would be 123.45, also I don't think it would have an outstanding amount anymore

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        penaltyAmountAccruing = 0,
This (penaltyAmountAccruing) would be 123.45, also I don't think it would have an outstanding amount anymore

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        penaltyAmountAccruing = 0,
This (penaltyAmountAccruing) would be 123.45, also I don't think it would have an outstanding amount anymore

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        penaltyAmountPosted = 123.45,
This is an accruing penalty, therefore there would be no posted amount

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        penaltyAmountAccruing = 0,
This (penaltyAmountAccruing) would be 400, also I don't think it would have an outstanding amount anymore

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/CalculationControllerISpec.scala
> +        penaltyAmountPosted = 123.45,
Also no outstanding amount now, i.e. None

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/IndexControllerISpec.scala
> +        penaltyAmountPosted = 200,
Posted would be outstanding + paid. So it would be 400.

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/IndexControllerISpec.scala
> +        penaltyAmountPosted = 200,
Posted would be outstanding + paid. So it would be 400.

2023-05-12 08:38 UTC, LewisMitchell commented on it/stubs/PenaltiesStub.scala
> +        penaltyAmountPosted = 1001.45,
This is an accruing penalty, therefore there would be no posted amount. Outstanding amount would be None and paid would also be None

2023-05-12 08:38 UTC, LewisMitchell commented on it/stubs/PenaltiesStub.scala
> +        penaltyAmountPosted = 1001.45,
This is an accruing penalty, therefore there would be no posted amount. Outstanding amount would be None and paid would also be None

2023-05-12 08:38 UTC, LewisMitchell commented on test/controllers/CalculationControllerSpec.scala
> +        penaltyAmountPosted = 1001.45,
Posted would be outstanding + paid. So it would be 1101.44

2023-05-12 08:38 UTC, LewisMitchell commented on test/models/GetPenaltyDetailsSpec.scala
> +           "penaltyAmountPosted": 1001.45,
This is an accruing penalty, therefore there would be no posted amount. No outstanding and paid amount also

2023-05-12 08:38 UTC, LewisMitchell commented on test/viewmodels/CalculationPageHelperSpec.scala
> +      penaltyAmountPosted = 1001.45,
This is an accruing penalty, therefore there would be no posted amount. Outstanding amount would be None and paid would also be None

2023-05-12 08:38 UTC, LewisMitchell commented on test/viewmodels/CalculationPageHelperSpec.scala
> +      penaltyAmountPosted = 1001.45,
This is an accruing penalty, therefore there would be no posted amount. Outstanding amount would be None and paid would also be None

2023-05-12 08:38 UTC, LewisMitchell commented on test/viewmodels/IndexPageHelperSpec.scala
> +                penaltyAmountPosted = 0,
penaltyAmountOutstanding would be None and penaltyAmountAccruing would be 144.21

2023-05-12 08:38 UTC, LewisMitchell commented on test/viewmodels/IndexPageHelperSpec.scala
> +                penaltyAmountPosted = 0,
penaltyAmountPosted = 144.21

2023-05-12 08:38 UTC, LewisMitchell commented on test/viewmodels/IndexPageHelperSpec.scala
> +        penaltyAmountPosted = 400,
penaltyAmountPosted = 410

2023-05-12 08:38 UTC, LewisMitchell commented on test/views/components/LatePaymentPenaltySummaryCardSpec.scala
> +        docWithAdditionalPenalty.select("h4").text() shouldBe "£1,001.45 penalty"
Might need to set penaltyAmountPosted in summaryCardModel to be 123.45

2023-05-12 08:38 UTC, LewisMitchell commented on test/views/components/LatePaymentPenaltySummaryCardSpec.scala
> +        docWithAdditionalPenaltyTenthsOfPence.select("h4").text() shouldBe "£124.40 penalty"
Based on the above, this would go back to £123.40

2023-05-12 08:38 UTC, LewisMitchell commented on it/controllers/IndexControllerISpec.scala
> +      parsedBody.select("#late-payment-penalties section header h4").text shouldBe "£200 penalty"
This would change back to £400 based on above comments

2023-05-12 08:38 UTC, LewisMitchell commented on test/views/components/LatePaymentPenaltySummaryCardSpec.scala
> +        doc.select("h4").text() shouldBe "£1,001.45 penalty"
Might need to set penaltyAmountPosted in summaryCardModel to be 400

2023-05-12 08:38 UTC, LewisMitchell commented on test/views/components/LatePaymentPenaltySummaryCardSpec.scala
> +      penaltyAmountPosted = 124.40,
I think this would be £123.40

2023-05-15 13:01 UTC, LewisMitchell requested changes

2023-05-15 13:01 UTC, LewisMitchell commented on test/views/components/LatePaymentPenaltySummaryCardSpec.scala
> +
Remove space please

2023-05-16 15:06 UTC, AndrewRButcher approved these changes

2023-05-16 15:09 UTC, merged