[PRM-2585] Added hidden text to LSP header
hmrc/penalties-frontend pull request #353
Opened 2023-05-24 13:53 UTC by JBlacklaws

2023-06-01 09:10 UTC, LewisMitchell requested changes

2023-06-01 09:10 UTC, LewisMitchell commented on test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
> +        doc.select("span").get(1).text() shouldBe "for penalty on late VAT return due 30 October 2069"
This check is a vulnerable to fail or prove the wrong thing:
```suggestion
        doc.select("a span").get(0).text() shouldBe "for penalty on late VAT return due 30 October 2069"
```

2023-06-01 09:10 UTC, LewisMitchell commented on test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
> +        docSubmitted.select("span").get(1).text() shouldBe "for late VAT return due on 30 October 2069"
This check is a vulnerable to fail or prove the wrong thing:
```suggestion
        docSubmitted.select("a span").get(0).text() shouldBe "for late VAT return due on 30 October 2069"
```

2023-06-01 09:10 UTC, LewisMitchell commented on test/views/components/LateSubmissionPenaltySummaryCardSpec.scala
> +        docWithFinancialLSP.select(".app-summary-card__title").get(0).text() shouldBe "£200 penalty for late submission of VAT due on 30 October 2069"
May be worth having a check for the visible text and the hidden text separately:
```suggestion
        docWithFinancialLSP.select(".app-summary-card__title").get(0).ownText() shouldBe "£200 penalty"
        docWithFinancialLSP.select(".app-summary-card__title span").get(0).ownText() shouldBe "for late submission of VAT due on 30 October 2069"
```

2023-06-01 09:10 UTC, LewisMitchell commented on it/controllers/IndexControllerISpec.scala
> +  val getPenaltyDetailsPayloadWithOverThreshold = GetPenaltyDetails(
This scenario doesn't give accurate data, this is a point applied after the threshold so ideally there needs to be other points

2023-06-01 09:11 UTC, LewisMitchell commented
Could you rebase as well please? And set the PR to ready for review

2023-06-02 12:47 UTC, AndrewRButcher approved these changes

2023-06-02 12:47 UTC, merged