[PRM-2601] - Refactor integration tests
hmrc/penalties-frontend pull request #355
Opened 2023-06-14 09:29 UTC by LewisMitchell

2023-06-14 11:00 UTC, JBlacklaws requested changes
Got a couple of places where the ComplianceStub is specifically called where it doesn't need to be, may be worth removing?
https://github.com/hmrc/penalties-frontend/blob/8592c6734868ada3109e4ee7383bbae6588f0acf/it/connectors/PenaltiesConnectorISpec.scala#L65
In addition, in the ComplianceStub, invalidComplianceDataStub and upstreamErrorStub are not called anywhere, so can be removed

2023-06-14 13:13 UTC, LewisMitchell commented
> Got a couple of places where the ComplianceStub is specifically called where it doesn't need to be, may be worth removing?
> 
> https://github.com/hmrc/penalties-frontend/blob/8592c6734868ada3109e4ee7383bbae6588f0acf/it/connectors/PenaltiesConnectorISpec.scala#L65
> 
> 
> In addition, in the ComplianceStub, invalidComplianceDataStub and upstreamErrorStub are not called anywhere, so can be removed

Thanks for spotting the compliance stub stuff, I've refactored that and the penalty details stub also. I couldn't find occurrences of `ComplianceStub is specifically called where it doesn't need to be`? Have you got a link to where this is occurring?

2023-06-14 13:57 UTC, JBlacklaws commented
> > Got a couple of places where the ComplianceStub is specifically called where it doesn't need to be, may be worth removing?
> > https://github.com/hmrc/penalties-frontend/blob/8592c6734868ada3109e4ee7383bbae6588f0acf/it/connectors/PenaltiesConnectorISpec.scala#L65
> > 
> > In addition, in the ComplianceStub, invalidComplianceDataStub and upstreamErrorStub are not called anywhere, so can be removed
> 
> Thanks for spotting the compliance stub stuff, I've refactored that and the penalty details stub also. I couldn't find occurrences of `ComplianceStub is specifically called where it doesn't need to be`? Have you got a link to where this is occurring?

In the code I linked originally, I believe you can remove the ComplianceStub. section and just have complianceDataStub()?

2023-06-15 13:43 UTC, JBlacklaws approved these changes

2023-06-15 14:35 UTC, merged