[PRM-2779] Updated TaxReturnStatusEnum to be optional and removed AddedFAP
hmrc/penalties-frontend pull request #368
Opened 2023-08-02 11:57 UTC by JBlacklaws

2023-08-02 12:02 UTC, LewisMitchell submitted a review, later dismissed

2023-08-02 12:02 UTC, LewisMitchell commented on app/config/featureSwitches/FeatureSwitch.scala
> +case object AddedFAPIsNone extends FeatureSwitch {
Could this feature switch name be made more generic? As it may relate to other changes we have planned.

2023-08-02 12:41 UTC, LewisMitchell commented on conf/application.conf
> +    added-fap-is-none = false
Could you raise a PR in prod config to disable this?

2023-08-02 13:51 UTC, JBlacklaws commented
Changes for in app-config: https://github.com/hmrc/app-config-production/pull/19299

2023-08-03 08:52 UTC, AndrewRButcher requested changes

2023-08-03 08:52 UTC, AndrewRButcher commented on app/config/featureSwitches/FeatureSwitch.scala
> +
Can we name it so it matches the backend feature switch?
```suggestion
case object EnableR5BProcessing extends FeatureSwitch {
  override val name: String = s"${FeatureSwitch.prefix}.enable-r5b-processing"
}
```

2023-08-03 11:30 UTC, AndrewRButcher approved these changes

2023-08-03 11:31 UTC, merged