PRM-2984 New Overpayment Charge added + content for summary card
hmrc/penalties-frontend pull request #381
Opened 2023-10-12 13:53 UTC by AndrewRButcher

2023-10-12 14:20 UTC, LewisMitchell requested changes

2023-10-12 14:20 UTC, LewisMitchell commented on app/viewmodels/SummaryCardHelper.scala
> +      case VATOverpaymentForTax => ""
Why is this blank?

2023-10-12 14:20 UTC, LewisMitchell commented on app/models/lpp/MainTransactionEnum.scala
> +  val VATOverpaymentForTax: MainTransactionEnum.Value = Value("4764")
Could there be a test for this?

2023-10-12 14:41 UTC, AndrewRButcher commented
addressed PR comments

2023-10-12 14:49 UTC, LewisMitchell commented
![image](https://github.com/hmrc/penalties-frontend/assets/53828896/7ca3038e-e729-49ae-abc8-af7dbb620b7f)

2023-10-13 11:02 UTC, LewisMitchell commented
Welsh being added as part of a different task

2023-10-13 11:02 UTC, merged