Prm 3116 added find out how to appeal link
hmrc/penalties-frontend pull request #392
Opened 2023-11-30 15:24 UTC by RoheelArshad

2023-11-30 16:32 UTC, AndrewRButcher requested changes

2023-11-30 16:32 UTC, AndrewRButcher commented on app/views/components/summaryCardLPP.scala.html
> +<p>@summaryCard.showFindOutHowToAppeal</p>
This line needs removing

2023-11-30 16:38 UTC, AndrewRButcher submitted a review, later dismissed

2023-12-01 14:09 UTC, JBlacklaws approved these changes

2023-12-01 14:11 UTC, merged